### ISSUE TITLE
Generera textlogg

### ISSUE THREAD

**Issue by linsjb** [SIMS-2020/IDEP#31]
Generera textloggar utifrån nedan json-blop
```json
{
  logType: 'FAULT',
  timeStamp: '2020-09-21T09:49:45.220Z',
  component: 'eis.Rocker_4',
  message: '(2188) Error event ((20): Motor fault. Please restart the instrument with the power switch.'
}
```

- [x] Generera textloggar utifrån profilen
- [ ] Generera timestamps som ligger bakåt i i tiden. Alltså inte bara "realtidsloggar".

**Comment by linsjb** [comment]
@amandaericson Hunnit börja på denna? :) 
Uppdaterar infon lite. Dels då det var inbakat att ordna till `profile.json` i samma issue, men den är nu utbruten till ett eget issue (#41). 

Men även för att vi fått lite mer information av Johan.

**Comment by linsjb** [comment]
Flyttat till sprint 3.

**Comment by amandaericson** [comment]
Aa fixar lite med den nu och tänkte sitta under helgen! Egentligen fixat en profile.json men tar bort den bara och använder den ni gjort i så fall

**Comment by linsjb** [comment]
@amandaericson Gör dom om generateLogs till en klass sedan? :)

**Comment by linsjb** [comment]
@amandaericson Även följa pep8 standarden. 
Alltså underscore-separerade variabelnamn :) https://www.python.org/dev/peps/pep-0008/
